version: '3.9'

services:
  mysql:
    image: mysql:8
    environment:
      # MYSQL_DATABASE: sample
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:${DB_PORT:-3306}'
    volumes:
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/my.cnf:/etc/conf.d/my.cnf
